import Lake
open Lake DSL

require algorithmLib from "../lib"

package algorithms where
  srcDir := "."

-- Benchmark algorithms
lean_lib RustBenchmarks
lean_lib PythonBenchmarks
lean_lib CsvBenchAlgorithm
lean_lib RegexBenchAlgorithm
lean_lib JsonBenchAlgorithm
lean_lib StringSearchAlgorithm
lean_lib WordCountAlgorithm
lean_lib SaxpyBenchAlgorithm
lean_lib HistogramBench1Algorithm
lean_lib HistogramBench4Algorithm
lean_lib MatmulBenchAlgorithm
lean_lib VecOpsBenchAlgorithm
lean_lib ReductionBenchAlgorithm
lean_lib GpuVecAddBenchAlgorithm
lean_lib GpuMatMulBenchAlgorithm
lean_lib GpuReductionBenchAlgorithm
lean_lib CudaSaxpyBenchAlgorithm
lean_lib GpuIterBenchAlgorithm
lean_lib SortBenchAlgorithm
lean_lib ClampSumBenchAlgorithm
lean_lib PandasBenchAlgorithm
lean_lib PandasFilterBenchAlgorithm
lean_lib RowAffineReduceBenchAlgorithm
lean_lib RowDotBenchAlgorithm
lean_lib CudaDecodeAttentionAlgorithm
lean_lib CudaDecoderLayerAlgorithm
lean_lib CudaGemvPersistAlgorithm
lean_lib CudaRmsNormPersistAlgorithm
lean_lib CudaSaxpyPersistAlgorithm
lean_lib CudaSoftmaxPersistAlgorithm
lean_lib CudaVecAddPersistAlgorithm

-- Application algorithms
lean_lib CliAlgorithm
lean_lib CompressAlgorithm
lean_lib CsvAlgorithm
lean_lib DrawAlgorithm
lean_lib FftAlgorithm
lean_lib LeanEvalAlgorithm
lean_lib MatmulAlgorithm
lean_lib RaytraceAlgorithm
lean_lib SatAlgorithm
lean_lib SceneAlgorithm
lean_lib BlackHoleAlgorithm
lean_lib Sha256Algorithm
lean_lib Qwen2Common
lean_lib Qwen2Algorithm
lean_lib Qwen2OnDiskAlgorithm
lean_lib WindowDemoAlgorithm
