import AlgorithmLib.Vocab.X86

/-! The machine code `CpuBenchAlgorithm` carries: LLVM's code for each
    workload's Rust kernel, with the arguments taken in registers. Each keeps
    the contract in `base/src/ffi/native.rs`. -/

namespace CpuBenchAsm

open AlgorithmLib.X86

/-- poly(p, n): LLVM's `k_poly_idiom`, 32 floats a trip in four ymm registers,
    `p` and `n` taken in registers. -/
def poly : Body := [
   mov rcx rsi,
   xor eax eax,
   test rcx rcx,
   je "8",
   mov rdx rdi,
   cmp rcx 0x4,
   jae "0",
   xor esi esi,
   jmp "5",
  lbl "0",
   cmp rcx 0x20,
   jae "1",
   xor esi esi,
   xor eax eax,
   jmp "3",
  lbl "1",
   vbroadcastss ymm1 (dword (rip "c0")),
   vbroadcastss ymm2 (dword (rip "c1")),
   vbroadcastss ymm3 (dword (rip "c2")),
   vbroadcastss ymm4 (dword (rip "c3")),
   vbroadcastss ymm5 (dword (rip "c4")),
   mov rsi rcx,
   and rsi 0xffffffffffffffe0,
   vxorps xmm0 xmm0 xmm0,
   xor eax eax,
   vxorps xmm6 xmm6 xmm6,
   vxorps xmm7 xmm7 xmm7,
   vxorps xmm8 xmm8 xmm8,
   p2align 4,
  lbl "2",
   vmovups ymm12 (ymmword (rdx + rax*4)),
   vmovups ymm11 (ymmword (rdx + rax*4 + 0x20)),
   vmovups ymm10 (ymmword (rdx + rax*4 + 0x40)),
   vmovups ymm9 (ymmword (rdx + rax*4 + 0x60)),
   add rax 0x20,
   vmulps ymm13 ymm12 ymm1,
   vaddps ymm13 ymm13 ymm2,
   vmulps ymm13 ymm12 ymm13,
   vaddps ymm13 ymm13 ymm3,
   vmulps ymm13 ymm12 ymm13,
   vaddps ymm13 ymm13 ymm4,
   vmulps ymm12 ymm12 ymm13,
   vmulps ymm13 ymm11 ymm1,
   vaddps ymm13 ymm13 ymm2,
   vaddps ymm12 ymm12 ymm5,
   vmulps ymm13 ymm11 ymm13,
   vxorps ymm0 ymm12 ymm0,
   vaddps ymm13 ymm13 ymm3,
   vmulps ymm13 ymm11 ymm13,
   vaddps ymm13 ymm13 ymm4,
   vmulps ymm11 ymm11 ymm13,
   vmulps ymm13 ymm10 ymm1,
   vaddps ymm13 ymm13 ymm2,
   vaddps ymm11 ymm11 ymm5,
   vmulps ymm13 ymm10 ymm13,
   vxorps ymm6 ymm11 ymm6,
   vaddps ymm13 ymm13 ymm3,
   vmulps ymm13 ymm10 ymm13,
   vaddps ymm13 ymm13 ymm4,
   vmulps ymm10 ymm10 ymm13,
   vmulps ymm13 ymm9 ymm1,
   vaddps ymm13 ymm13 ymm2,
   vaddps ymm10 ymm10 ymm5,
   vmulps ymm13 ymm9 ymm13,
   vxorps ymm7 ymm10 ymm7,
   vaddps ymm13 ymm13 ymm3,
   vmulps ymm13 ymm9 ymm13,
   vaddps ymm13 ymm13 ymm4,
   vmulps ymm9 ymm9 ymm13,
   vaddps ymm9 ymm9 ymm5,
   vxorps ymm8 ymm8 ymm9,
   cmp rsi rax,
   jne "2",
   vxorps ymm0 ymm6 ymm0,
   vxorps ymm0 ymm7 ymm0,
   vxorps ymm0 ymm8 ymm0,
   vextractf128 xmm1 ymm0 0x1,
   vxorps xmm0 xmm0 xmm1,
   vshufps xmm1 xmm0 xmm0 0xee,
   vxorps xmm0 xmm0 xmm1,
   vshufps xmm1 xmm0 xmm0 0x55,
   vxorps xmm0 xmm0 xmm1,
   vmovd eax xmm0,
   cmp rcx rsi,
   je "7",
   test cl 0x1c,
   je "5",
  lbl "3",
   vbroadcastss xmm1 (dword (rip "c0")),
   vbroadcastss xmm2 (dword (rip "c1")),
   vbroadcastss xmm3 (dword (rip "c2")),
   vbroadcastss xmm4 (dword (rip "c3")),
   vbroadcastss xmm5 (dword (rip "c4")),
   mov rdi rsi,
   mov rsi rcx,
   and rsi 0xfffffffffffffffc,
   vmovd xmm0 eax,
   p2align 4,
  lbl "4",
   vmovups xmm6 (xmmword (rdx + rdi*4)),
   add rdi 0x4,
   vmulps xmm7 xmm6 xmm1,
   vaddps xmm7 xmm7 xmm2,
   vmulps xmm7 xmm6 xmm7,
   vaddps xmm7 xmm7 xmm3,
   vmulps xmm7 xmm6 xmm7,
   vaddps xmm7 xmm7 xmm4,
   vmulps xmm6 xmm6 xmm7,
   vaddps xmm6 xmm6 xmm5,
   vpxor xmm0 xmm0 xmm6,
   cmp rsi rdi,
   jne "4",
   vpshufd xmm1 xmm0 0xee,
   vpxor xmm0 xmm0 xmm1,
   vpshufd xmm1 xmm0 0x55,
   vpxor xmm0 xmm0 xmm1,
   vmovd eax xmm0,
   cmp rcx rsi,
   je "7",
  lbl "5",
   vmovss xmm0 (dword (rip "c0")),
   vmovss xmm1 (dword (rip "c1")),
   vmovss xmm2 (dword (rip "c2")),
   vmovss xmm3 (dword (rip "c3")),
   vmovss xmm4 (dword (rip "c4")),
   p2align 4,
  lbl "6",
   vmovss xmm5 (dword (rdx + rsi*4)),
   inc rsi,
   vmulss xmm6 xmm5 xmm0,
   vaddss xmm6 xmm6 xmm1,
   vmulss xmm6 xmm5 xmm6,
   vaddss xmm6 xmm6 xmm2,
   vmulss xmm6 xmm5 xmm6,
   vaddss xmm6 xmm6 xmm3,
   vmulss xmm5 xmm5 xmm6,
   vaddss xmm5 xmm5 xmm4,
   vmovd edi xmm5,
   xor eax edi,
   cmp rcx rsi,
   jne "6",
  lbl "7",
   mov eax eax,
  lbl "8",
   vzeroupper,
   ret,
   p2align 2,
  lbl "c0",
   f32 0.0625,
   p2align 2,
  lbl "c1",
   f32 (-0.125),
   p2align 2,
  lbl "c2",
   f32 0.25,
   p2align 2,
  lbl "c3",
   f32 (-0.5),
   p2align 2,
  lbl "c4",
   f32 1.0]

/-- stream(src, n, dst): LLVM's `stream_nt`, a copy by non-temporal stores
    (`vmovntdq`), which Cranelift has no form for. -/
def stream : Body := [
   cmp rsi 0x4,
   jb "1",
   mov rax rsi,
   shr rax 0x2,
   add rdi 0x60,
   xor ecx ecx,
   mov r8 rdx,
   p2align 4,
  lbl "0",
   vmovaps ymm0 (ymmword (rdi - 0x60)),
   vmovntdq (ymmword r8) ymm0,
   lea r9 (mem (r8 + 0x20)),
   add rcx 0x4,
   vmovaps ymm0 (ymmword (rdi - 0x40)),
   vmovntdq (ymmword r9) ymm0,
   lea r9 (mem (r8 + 0x40)),
   vmovaps ymm0 (ymmword (rdi - 0x20)),
   vmovntdq (ymmword r9) ymm0,
   lea r9 (mem (r8 + 0x60)),
   sub r8 0xffffffffffffff80,
   vmovaps ymm0 (ymmword rdi),
   vmovntdq (ymmword r9) ymm0,
   sub rdi 0xffffffffffffff80,
   cmp rcx rax,
   jb "0",
  lbl "1",
   sfence,
   mov rax (qword (rdx + rsi*8 - 0x8)),
   shr rsi 1,
   xor rax (qword (rdx + rsi*8)),
   vzeroupper,
   ret]

end CpuBenchAsm
